# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build-java:  
    #runs-on: ${{matrix.os}}
    #strategy:
      #matrix:
        #os: [ubuntu-latest,windows-latest,macOS-latest]
   
    #Note that on Ubuntu I don't need to install docker to create and push images, that's whay I've commented out the previous lines   
    runs-on: ubuntu-latest
    environment: build-deploy-push-environment
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: rick69/test-github-actions
        tags: v2_rick
        registry: docker.io	  
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    
